package io.github.xtoolkit.mir.level.presentation.multi

import io.github.xtoolkit.mir.level.core.domain.Level
import io.github.xtoolkit.mir.playground.core.domain.Playground

private val playgrounds = listOf(
    Playground(0, listOf("abed", "bade", "bead")),
    Playground(0, listOf("abet", "beat", "beta")),
    Playground(0, listOf("abets", "baste", "betas", "beast", "beats")),
    Playground(0, listOf("abut", "tabu", "tuba")),
    Playground(0, listOf("acme", "came", "mace")),
    Playground(0, listOf("acre", "care", "race")),
    Playground(0, listOf("acres", "cares", "races", "scare")),
    Playground(0, listOf("actors", "costar", "castor")),
    Playground(0, listOf("actress", "casters", "recasts")),
    Playground(0, listOf("airmen", "marine", "remain")),
    Playground(0, listOf("alert", "alter", "later")),
    Playground(0, listOf("alerted", "altered", "related", "treadle")),
    Playground(0, listOf("ales", "leas", "sale", "seal")),
    Playground(0, listOf("aligned", "dealing", "leading")),
    Playground(0, listOf("allergy", "gallery", "largely", "regally")),
    Playground(0, listOf("amen", "mane", "mean", "name")),
    Playground(0, listOf("anew", "wane", "wean")),
    Playground(0, listOf("angel", "angle", "glean")),
    Playground(0, listOf("antler", "learnt", "rental")),
    Playground(0, listOf("apt", "pat", "tap")),
    Playground(0, listOf("arches", "chaser", "search")),
    Playground(0, listOf("are", "ear", "era")),
    Playground(0, listOf("arm", "mar", "ram")),
    Playground(0, listOf("arrest", "rarest", "raters", "starer")),
    Playground(0, listOf("artist", "strait", "traits")),
    Playground(0, listOf("arts", "rats", "star", "tars")),
    Playground(0, listOf("arcs", "cars", "scar")),
    Playground(0, listOf("ascent", "secant", "stance")),
    Playground(0, listOf("ascot", "coats", "coast", "tacos")),
    Playground(0, listOf("asleep", "elapse", "please")),
    Playground(0, listOf("asp", "pas", "sap", "spa")),
    Playground(0, listOf("aspired", "despair", "diapers", "praised")),
    Playground(0, listOf("asps", "pass", "saps", "spas")),
    Playground(0, listOf("assert", "asters", "stares")),
    Playground(0, listOf("aster", "rates", "stare", "taser", "tears")),
    Playground(0, listOf("ate", "eat", "eta", "tea")),
    Playground(0, listOf("aridest", "astride", "staider", "tardies", "tirades")),
    Playground(0, listOf("auctioned", "cautioned", "education")),
    Playground(0, listOf("awls", "laws", "slaw")),
    Playground(0, listOf("baker", "brake", "break")),
    Playground(0, listOf("bard", "brad", "drab")),
    Playground(0, listOf("bared", "beard", "bread", "debar")),
    Playground(0, listOf("barely", "barley", "bleary")),
    Playground(0, listOf("bats", "stab", "tabs")),
    Playground(0, listOf("begin", "being", "binge")),
    Playground(0, listOf("below", "bowel", "elbow")),
    Playground(0, listOf("bleats", "stable", "tables")),
    Playground(0, listOf("bluest", "bluets", "bustle", "sublet", "subtle")),
    Playground(0, listOf("bores", "robes", "sober")),
    Playground(0, listOf("brag", "garb", "grab")),
    Playground(0, listOf("calipers", "replicas", "spiracle")),
    Playground(0, listOf("caller", "cellar", "recall")),
    Playground(0, listOf("canter", "nectar", "recant", "trance")),
    Playground(0, listOf("canters", "nectars", "recants", "scanter", "trances")),
    Playground(0, listOf("capes", "paces", "space")),
    Playground(0, listOf("caret", "cater", "crate", "trace")),
    Playground(0, listOf("carets", "caters", "caster", "crates", "reacts", "recast", "traces")),
    Playground(0, listOf("catered", "created", "reacted")),
    Playground(0, listOf("cider", "cried", "dicer")),
    Playground(0, listOf("claimed", "decimal", "declaim", "medical")),
    Playground(0, listOf("claps", "clasp", "scalp")),
    Playground(0, listOf("code", "coed", "deco")),
    Playground(0, listOf("construe", "counters", "recounts", "trounces")),
    Playground(0, listOf("corset", "escort", "sector")),
    Playground(0, listOf("cratered", "retraced", "terraced")),
    Playground(0, listOf("cruel", "lucre", "ulcer")),
    Playground(0, listOf("dale", "deal", "lade", "lead")),
    Playground(0, listOf("dare", "dear", "read")),
    Playground(0, listOf("danger", "gander", "garden", "ranged")),
    Playground(0, listOf("darters", "retards", "starred", "traders")),
    Playground(0, listOf("dater", "rated", "trade", "tread")),
    Playground(0, listOf("daters", "trades", "treads", "stared")),
    Playground(0, listOf("dates", "sated", "stead")),
    Playground(0, listOf("dearth", "hatred", "thread")),
    Playground(0, listOf("dearths", "hardest", "hatreds", "threads", "trashed")),
    Playground(0, listOf("decanter", "cantered", "recanted")),
    Playground(0, listOf("deigns", "design", "signed", "singed")),
    Playground(0, listOf("deist", "diets", "edits", "sited", "tides")),
    Playground(0, listOf("demerit", "merited", "mitered")),
    Playground(0, listOf("denter", "rented", "tender")),
    Playground(0, listOf("deltas", "lasted", "slated")),
    Playground(0, listOf("demo", "dome", "mode")),
    Playground(0, listOf("desert", "deters", "rested")),
    Playground(0, listOf("detail", "dilate", "tailed")),
    Playground(0, listOf("detains", "instead", "sainted", "stained")),
    Playground(0, listOf("detour", "routed", "toured")),
    Playground(0, listOf("diaper", "paired", "repaid")),
    Playground(0, listOf("diet", "edit", "tide", "tied")),
    Playground(0, listOf("direst", "driest", "stride")),
    Playground(0, listOf("discounter", "introduces", "reductions")),
    Playground(0, listOf("does", "dose", "odes")),
    Playground(0, listOf("doters", "sorted", "stored")),
    Playground(0, listOf("dowry", "rowdy", "wordy")),
    Playground(0, listOf("drapes", "padres", "parsed", "rasped", "spared", "spread")),
    Playground(0, listOf("drawer", "redraw", "reward", "warder", "warred")),
    Playground(0, listOf("dues", "sued", "used")),
    Playground(0, listOf("duster", "rudest", "rusted")),
    Playground(0, listOf("earned", "endear", "neared")),
    Playground(0, listOf("earnest", "eastern", "nearest")),
    Playground(0, listOf("earns", "nears", "saner", "snare")),
    Playground(0, listOf("ears", "eras", "sear")),
    Playground(0, listOf("earth", "hater", "heart")),
    Playground(0, listOf("east", "eats", "sate", "seat", "teas")),
    Playground(0, listOf("elan", "lane", "lean")),
    Playground(0, listOf("emigrants", "mastering", "streaming")),
    Playground(0, listOf("emoter", "meteor", "remote")),
    Playground(0, listOf("enlarge", "general", "gleaner")),
    Playground(0, listOf("emit", "item", "mite", "time")),
    Playground(0, listOf("emits", "items", "mites", "smite", "times")),
    Playground(0, listOf("endive", "envied", "veined")),
    Playground(0, listOf("enlist", "inlets", "listen", "silent", "tinsel")),
    Playground(0, listOf("enters", "nester", "resent", "tenser")),
    Playground(0, listOf("eons", "nose", "ones")),
    Playground(0, listOf("esprit", "priest", "sprite", "stripe")),
    Playground(0, listOf("esprits", "persist", "spriest", "sprites", "stripes")),
    Playground(0, listOf("ester", "reset", "steer", "terse", "trees")),
    Playground(0, listOf("ether", "there", "three")),
    Playground(0, listOf("evil", "live", "veil", "vile")),
    Playground(0, listOf("filets", "itself", "stifle")),
    Playground(0, listOf("filter", "lifter", "trifle")),
    Playground(0, listOf("flow", "fowl", "wolf")),
    Playground(0, listOf("forest", "fortes", "foster", "softer")),
    Playground(0, listOf("glare", "lager", "large", "regal")),
    Playground(0, listOf("gilder", "girdle", "glider")),
    Playground(0, listOf("gnus", "guns", "snug", "sung")),
    Playground(0, listOf("goer", "gore", "ogre")),
    Playground(0, listOf("gory", "gyro", "orgy")),
    Playground(0, listOf("gust", "guts", "tugs")),
    Playground(0, listOf("hare", "hear", "rhea")),
    Playground(0, listOf("hares", "hears", "rheas", "share", "shear")),
    Playground(0, listOf("heaps", "phase", "shape")),
    Playground(0, listOf("heros", "hoers", "horse", "shore")),
    Playground(0, listOf("hoes", "hose", "shoe")),
    Playground(0, listOf("hops", "posh", "shop")),
    Playground(0, listOf("ideals", "ladies", "sailed")),
    Playground(0, listOf("inks", "sink", "skin")),
    Playground(0, listOf("ires", "rise", "sire")),
    Playground(0, listOf("kale", "lake", "leak")),
    Playground(0, listOf("lair", "liar", "rail")),
    Playground(0, listOf("lame", "male", "meal")),
    Playground(0, listOf("lameness", "nameless", "salesman")),
    Playground(0, listOf("lament", "mantel", "mantle", "mental")),
    Playground(0, listOf("lapse", "leaps", "pales", "peals", "pleas", "sepal")),
    Playground(0, listOf("last", "salt", "slat")),
    Playground(0, listOf("late", "tale", "teal")),
    Playground(0, listOf("leap", "pale", "peal", "plea")),
    Playground(0, listOf("leapt", "petal", "plate", "pleat")),
    Playground(0, listOf("least", "slate", "stale", "steal", "tales", "teals")),
    Playground(0, listOf("lemons", "melons", "solemn")),
    Playground(0, listOf("limes", "miles", "slime", "smile")),
    Playground(0, listOf("list", "silt", "slit")),
    Playground(0, listOf("lips", "lisp", "slip")),
    Playground(0, listOf("lisper", "perils", "pliers")),
    Playground(0, listOf("lister", "liters", "litres", "relist", "tilers")),
    Playground(0, listOf("livers", "silver", "sliver")),
    Playground(0, listOf("loop", "polo", "pool")),
    Playground(0, listOf("looped", "poodle", "pooled")),
    Playground(0, listOf("loops", "polos", "pools", "sloop", "spool")),
    Playground(0, listOf("lopes", "poles", "slope")),
    Playground(0, listOf("lots", "lost", "slot")),
    Playground(0, listOf("lusters", "results", "rustles")),
    Playground(0, listOf("manes", "manse", "means", "names")),
    Playground(0, listOf("marines", "remains", "seminar")),
    Playground(0, listOf("mast", "mats", "tams")),
    Playground(0, listOf("master", "stream", "tamers")),
    Playground(0, listOf("mate", "meat", "tame", "team")),
    Playground(0, listOf("mates", "meats", "steam", "tames", "teams")),
    Playground(0, listOf("merit", "mitre", "remit", "timer")),
    Playground(0, listOf("merits", "mister", "miters", "mitres", "remits", "timers")),
    Playground(0, listOf("mesa", "same", "seam")),
    Playground(0, listOf("nails", "slain", "snail")),
    Playground(0, listOf("naive", "ravine", "vainer")),
    Playground(0, listOf("nape", "neap", "pane")),
    Playground(0, listOf("naps", "pans", "snap", "span")),
    Playground(0, listOf("nets", "nest", "sent", "tens")),
    Playground(0, listOf("nope", "open", "peon", "pone")),
    Playground(0, listOf("noter", "toner", "tenor")),
    Playground(0, listOf("notes", "onset", "stone", "tones")),
    Playground(0, listOf("now", "own", "won")),
    Playground(0, listOf("observe", "obverse", "verbose")),
    Playground(0, listOf("opt", "pot", "top")),
    Playground(0, listOf("opts", "post", "pots", "stop", "tops")),
    Playground(0, listOf("owns", "snow", "sown")),
    Playground(0, listOf("paled", "pedal", "plead")),
    Playground(0, listOf("palest", "pastel", "petals", "plates", "pleats", "staple")),
    Playground(0, listOf("panel", "penal", "plane")),
    Playground(0, listOf("pares", "parse", "pears", "rapes", "reaps", "spare", "spear")),
    Playground(0, listOf("parley", "pearly", "player", "replay")),
    Playground(0, listOf("parroted", "predator", "prorated", "teardrop")),
    Playground(0, listOf("pars", "raps", "rasp", "spar")),
    Playground(0, listOf("parses", "passer", "spares", "sparse", "spears")),
    Playground(0, listOf("paltry", "partly", "raptly")),
    Playground(0, listOf("parts", "strap", "traps")),
    Playground(0, listOf("parse", "pears", "spare", "spear")),
    Playground(0, listOf("parsley", "parleys", "players", "replays", "sparely")),
    Playground(0, listOf("part", "rapt", "trap")),
    Playground(0, listOf("parties", "pastier", "pirates", "traipse")),
    Playground(0, listOf("past", "pats", "spat", "taps")),
    Playground(0, listOf("paste", "peats", "septa", "spate", "tapes")),
    Playground(0, listOf("paws", "swap", "wasp")),
    Playground(0, listOf("pelts", "slept", "spelt")),
    Playground(0, listOf("pertness", "presents", "serpents")),
    Playground(0, listOf("pest", "pets", "step")),
    Playground(0, listOf("piers", "pries", "spire")),
    Playground(0, listOf("pines", "snipe", "spine")),
    Playground(0, listOf("pinto", "piton", "point"))
).chunked(30)

val initialLevels = mutableListOf<Pair<Level, List<Playground>>>().apply {
    addAll(
        listOf(
            "Basic",
            "intermediate",
            "advanced",
            "expert",
            "professional",
            "master"
        ).mapIndexed { i, item ->
            Level(0, item) to playgrounds[i]
        })
}

